APPLE: [0,3,0,1,0]
MUSHROOM_STEW: [2,0,2,2,2]
BREAD: [1,2,1,4,3]
PORKCHOP: [3,0,2,1,3]
COOKED_PORKCHOP: [3,0,2,1,3]
COD: [2,0,2,1,3]
SALMON: [4,0,2,0,2]
TROPICAL_FISH: [2,0,2,0,2]
PUFFERFISH: [1,0,2,0,2]
COOKED_COD: [2,0,2,1,3]
COOKED_SALMON: [4,0,2,0,2]
COOKIE: [2,4,1,3,2]
MELON_SLICE: [0,3,0,2,1]
DRIED_KELP: [2,2,4,2,2]
BEEF: [3,0,2,2,3]
COOKED_BEEF: [3,0,2,2,3]
CHICKEN: [2,0,2,1,2]
COOKED_CHICKEN: [2,0,2,1,2]
ROTTEN_FLESH: [1,0,1,1,1]
SPIDER_EYE: [1,0,1,1,2]
CARROT: [0,2,1,3,1]
POTATO: [0,1,0,4,1]
BAKED_POTATO: [0,3,0,1,0]
POISONOUS_POTATO: [0,3,0,1,0]
PUMPKIN_PIE: [0,3,0,1,0]
RABBIT: [0,3,0,1,0]
COOKED_RABBIT: [0,3,0,1,0]
RABBIT STEW: [0,3,0,1,0]
MUTTON: [0,3,0,1,0]
COOKED_MUTTON: [0,3,0,1,0]
CHORUS_FRUIT: [0,3,0,1,0]
BEETROOT: [0,3,0,1,0]
BEETROOT_SOUP: [0,3,0,1,0]
SUSPICIOUS_STEW: [0,3,0,1,0]
SWEET_BERRIES: [0,3,0,1,0]
GLOW_BERRIES: [0,3,0,1,0]
HONEY_BOTTLE: [0,3,0,1,0]
CAKE: [0,3,0,1,0]
